import os
from typing import List, Dict, Any, Optional
import chromadb
from chromadb.utils import embedding_functions

class ContractVectorStore:
    """
    Manages local vector storage and retrieval of contract chunks using ChromaDB.
    """
    def __init__(self, db_dir: str = "data/db", collection_name: str = "msa_contracts"):
        """
        Args:
            db_dir: Path to persist the local ChromaDB database files.
            collection_name: Name of the collection where vector embeddings are stored.
        """
        self.db_dir = db_dir
        self.collection_name = collection_name
        
        # Ensure database directory exists
        os.makedirs(db_dir, exist_ok=True)
        
        # Initialize persistent Chroma client
        self.client = chromadb.PersistentClient(path=db_dir)
        
        # Use sentence-transformers (all-MiniLM-L6-v2 is fast, compact, and runs locally on Mac)
        self.embedding_function = embedding_functions.SentenceTransformerEmbeddingFunction(
            model_name="all-MiniLM-L6-v2"
        )
        
        # Create or fetch the collection
        self.collection = self.client.get_or_create_collection(
            name=collection_name,
            embedding_function=self.embedding_function
        )

    def add_contract_chunks(self, contract_name: str, chunks: List[Dict[str, Any]]) -> None:
        """
        Embeds and adds contract text chunks to the vector database.
        
        Args:
            contract_name: Unique identifier for the contract (e.g., filename).
            chunks: List of chunk dicts generated by ContractChunker.
        """
        if not chunks:
            return

        ids = []
        documents = []
        metadatas = []

        for idx, chunk in enumerate(chunks):
            # Unique ID for each chunk: contract_name_chunkIndex
            chunk_id = f"{contract_name}_chunk_{idx}"
            
            ids.append(chunk_id)
            documents.append(chunk["text"])
            
            meta = {
                "contract_name": contract_name,
                "chunk_idx": idx,
                "start_idx": chunk["start_idx"],
                "end_idx": chunk["end_idx"]
            }
            if "parent_text" in chunk:
                meta["parent_text"] = chunk["parent_text"]
                meta["parent_start_idx"] = chunk["parent_start_idx"]
                meta["parent_end_idx"] = chunk["parent_end_idx"]
                
            metadatas.append(meta)

        self.collection.add(
            ids=ids,
            documents=documents,
            metadatas=metadatas
        )
        print(f"Added {len(chunks)} chunks for contract '{contract_name}' to vector store.")

    def search_relevant_chunks(
        self, 
        contract_name: str, 
        query: str, 
        limit: int = 3
    ) -> List[Dict[str, Any]]:
        """
        Queries the vector store for chunks matching the search text, filtered by contract.
        
        Args:
            contract_name: The contract to search within.
            query: The query text (e.g., "Governing Law").
            limit: The maximum number of chunks to return.
            
        Returns:
            A list of retrieved chunks with metadata.
        """
        results = self.collection.query(
            query_texts=[query],
            n_results=limit,
            where={"contract_name": contract_name}
        )

        retrieved_chunks = []
        seen_texts = set()
        
        # Extract matches if any are found
        if results and "documents" in results and results["documents"]:
            # ChromaDB returns nested arrays, retrieve the first query results
            documents = results["documents"][0]
            metadatas = results["metadatas"][0]
            distances = results["distances"][0] if "distances" in results else [0.0] * len(documents)

            for doc, meta, dist in zip(documents, metadatas, distances):
                # Retrieve parent text if present, otherwise fallback to child text
                text_content = meta.get("parent_text", doc)
                
                # Deduplicate by parent text content
                norm_text = " ".join(text_content.split())
                if norm_text in seen_texts:
                    continue
                seen_texts.add(norm_text)
                
                retrieved_chunks.append({
                    "text": text_content,
                    "metadata": meta,
                    "distance": dist
                })

        return retrieved_chunks

    def delete_contract(self, contract_name: str) -> None:
        """
        Deletes all vector embeddings associated with a specific contract.
        """
        self.collection.delete(
            where={"contract_name": contract_name}
        )
        print(f"Deleted all records for contract '{contract_name}' from vector store.")

# Example usage for testing
if __name__ == "__main__":
    store = ContractVectorStore(db_dir="data/test_db", collection_name="test_collection")
    
    contract = "sample_msa.txt"
    test_chunks = [
        {"text": "Governing Law. This agreement is governed by the laws of New York.", "start_idx": 0, "end_idx": 68},
        {"text": "Payment Terms. All payments are due within net 45 days.", "start_idx": 69, "end_idx": 124},
        {"text": "Termination. Notice of termination must be given 30 days prior.", "start_idx": 125, "end_idx": 188}
    ]
    
    # Store chunks
    store.add_contract_chunks(contract, test_chunks)
    
    # Search governing law
    print("\n--- Searching 'Governing Law' ---")
    matches = store.search_relevant_chunks(contract, "What state law governs this contract?", limit=1)
    for m in matches:
        print(f"Match: {m['text']} (Distance: {m['distance']:.4f})")
        
    # Clean up
    store.delete_contract(contract)
